services:
  client:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - "./client/src:/app/src"
      - "./client/index.html:/app/index.html"
    environment:
      - CHOKIDAR_USEPOLLING=true
