services:
  client:
    build:
      context: ./client
      dockerfile: test.Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - "./client/__tests__:/app/__tests__"
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    build:
      context: ./server
      dockerfile: test.Dockerfile
    ports:
      - "80:80"
    volumes:
      - "./server/__tests__:/app/__tests__"
      - "./server/src:/app/src"
      - "./server/vitest.setup.ts:/app/vitest.setup.ts"
    environment:
      - CHOKIDAR_USEPOLLING=true

  database:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - server/.env.test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
