services:
  client:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - "./client/src:/app/src"
      - "./client/index.html:/app/index.html"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    ports:
      - "80:80"
    volumes:
      - "./server/src:/app/src"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - server/.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
